# lightning.pytorch==2.4.0
seed_everything: true
trainer:
  callbacks:
    class_path: PredictionWriter
    init_args:
      output_dir: 'predictions/_3_augmented_unet'
  logger: false
  accelerator: 'cuda'
  enable_progress_bar: true
  enable_model_summary: true
  inference_mode: true
model:
  net:
    class_path: segmentation_models_pytorch.Unet
    init_args:
      encoder_name: 'resnet34'
      encoder_weights: 'imagenet'
      in_channels: 3
      decoder_use_batchnorm: true
      decoder_attention_type: 'scse'
      classes: 1
  criterion:
    class_path: segmentation_models_pytorch.losses.JaccardLoss
    init_args:
      mode: 'binary'
      from_logits: true
data:
  class_path: TomatoLeafDataModule
  init_args:
    data_dir: data/leaf_veins
    batch_size: 1
    num_workers: 2
return_predictions: false
ckpt_path: null
